//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManageWebsite.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromissoryNote
    {
        public string Id { get; set; }
        public string ReaderId { get; set; }
        public string UserId { get; set; }
        public string OwnerId { get; set; }
        public string BookId { get; set; }
        public System.DateTime BorrowedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Cost { get; set; }
        public byte Status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual User User { get; set; }
    }
}
