//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManageWebsite.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regulation
    {
        public int Id { get; set; }
        public string RegulationsContent { get; set; }
        public string OwnerId { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
