//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.PromissoryNoteDetails = new HashSet<PromissoryNoteDetail>();
        }
    
        public string BId { get; set; }
        public string BName { get; set; }
        public string BAuthor { get; set; }
        public string BPublisher { get; set; }
        public double BPrice { get; set; }
        public int BQuantity { get; set; }
        public System.DateTime BInportTime { get; set; }
        public int BYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromissoryNoteDetail> PromissoryNoteDetails { get; set; }
    }
}
