//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromissoryNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromissoryNote()
        {
            this.PromissoryNoteDetails = new HashSet<PromissoryNoteDetail>();
        }
    
        public string PNId { get; set; }
        public string RId { get; set; }
        public string UId { get; set; }
    
        public virtual Reader Reader { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromissoryNoteDetail> PromissoryNoteDetails { get; set; }
    }
}
