//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.PromissoryNotes = new HashSet<PromissoryNote>();
        }
    
        public string UId { get; set; }
        public string UName { get; set; }
        public string UPhone { get; set; }
        public string UAddress { get; set; }
        public string UUsername { get; set; }
        public string UPassword { get; set; }
        public byte UType { get; set; }
        public byte UStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromissoryNote> PromissoryNotes { get; set; }
    }
}
