//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string PId { get; set; }
        public string PName { get; set; }
        public double Price { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
