//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Price { get; set; }
        public int Quantity { get; set; }
        public string DateOfSales { get; set; }
        public string ModeOfPayment { get; set; }
    }
}
