//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace watchShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_inport_invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_inport_invoice()
        {
            this.tb_details_inport = new HashSet<tb_details_inport>();
        }
    
        public int inportInvoiceID { get; set; }
        public Nullable<int> supplierID { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> staffID { get; set; }
        public Nullable<int> totalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_details_inport> tb_details_inport { get; set; }
        public virtual tb_supplier tb_supplier { get; set; }
        public virtual tb_users tb_users { get; set; }
    }
}
