//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace watchShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tb_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_products()
        {
            this.tb_cart = new HashSet<tb_cart>();
            this.tb_details_export = new HashSet<tb_details_export>();
            this.tb_details_inport = new HashSet<tb_details_inport>();
            this.tb_order = new HashSet<tb_order>();
            this.tb_wishlist = new HashSet<tb_wishlist>();

            pic = "~/Content/images/items/add-product.png";
        }
    
        public int watchID { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> price { get; set; }
        public string color { get; set; }
        public string desc_ { get; set; }
        public string pic { get; set; }
        public Nullable<int> producerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cart> tb_cart { get; set; }
        public virtual tb_category tb_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_details_export> tb_details_export { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_details_inport> tb_details_inport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_order> tb_order { get; set; }
        public virtual tb_producer tb_producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_wishlist> tb_wishlist { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
