//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3H_K35DL1_Winforms.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public string MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> B { get; set; }
        public Nullable<double> A { get; set; }
        public int KiHoc { get; set; }
    
        public virtual HocKi HocKi { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
