//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3H_K35DL1_Winforms.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoiSinhVien
    {
        public int ID { get; set; }
        public string MaSV { get; set; }
        public string TinhTrang { get; set; }
        public string YKienPhanHoi { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
