//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3H_K35DL1_Winforms.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string ID { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> PDT { get; set; }
        public Nullable<bool> GV { get; set; }
        public Nullable<bool> SV { get; set; }
        public Nullable<bool> BU { get; set; }
        public Nullable<bool> RT { get; set; }
        public Nullable<bool> FULLC { get; set; }
    }
}
