//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3H_K34DL1_WebMVC5.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giay()
        {
            this.CT_HDNhap = new HashSet<CT_HDNhap>();
            this.CT_HDXuat = new HashSet<CT_HDXuat>();
        }
    
        public int MaGiay { get; set; }
        public string TenGiay { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<int> MaLG { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> KichCo { get; set; }
        public string MauSac { get; set; }
        public Nullable<int> Gia { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HDNhap> CT_HDNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HDXuat> CT_HDXuat { get; set; }
        public virtual LoaiGiay LoaiGiay { get; set; }
        public virtual NhaSX NhaSX { get; set; }
    }
}
